global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    metrics_path: "/actuator/promotheus"
    static_configs:
      - targets: ['host.docker.internal:9090']